# -*- coding: utf-8 -*-
"""GENERADO por tools/gen_names.py desde PokeAPI - no editar a mano.

Nombres oficiales por idioma. FR y DE van en mayusculas y sin
acentos (fuente CP437, un byte por caracter); JA y KO van en
UTF-8 tal cual, porque se pintan con una fuente U8g2.
"""

LOCAL_NAMES = {
    1: {'fr': 'BULBIZARRE', 'de': 'BISASAM', 'ja': 'フシギダネ', 'ko': '이상해씨'},
    2: {'fr': 'HERBIZARRE', 'de': 'BISAKNOSP', 'ja': 'フシギソウ', 'ko': '이상해풀'},
    3: {'fr': 'FLORIZARRE', 'de': 'BISAFLOR', 'ja': 'フシギバナ', 'ko': '이상해꽃'},
    4: {'fr': 'SALAMECHE', 'de': 'GLUMANDA', 'ja': 'ヒトカゲ', 'ko': '파이리'},
    5: {'fr': 'REPTINCEL', 'de': 'GLUTEXO', 'ja': 'リザード', 'ko': '리자드'},
    6: {'fr': 'DRACAUFEU', 'de': 'GLURAK', 'ja': 'リザードン', 'ko': '리자몽'},
    7: {'fr': 'CARAPUCE', 'de': 'SCHIGGY', 'ja': 'ゼニガメ', 'ko': '꼬부기'},
    8: {'fr': 'CARABAFFE', 'de': 'SCHILLOK', 'ja': 'カメール', 'ko': '어니부기'},
    9: {'fr': 'TORTANK', 'de': 'TURTOK', 'ja': 'カメックス', 'ko': '거북왕'},
    10: {'fr': 'CHENIPAN', 'de': 'RAUPY', 'ja': 'キャタピー', 'ko': '캐터피'},
    11: {'fr': 'CHRYSACIER', 'de': 'SAFCON', 'ja': 'トランセル', 'ko': '단데기'},
    12: {'fr': 'PAPILUSION', 'de': 'SMETTBO', 'ja': 'バタフリー', 'ko': '버터플'},
    13: {'fr': 'ASPICOT', 'de': 'HORNLIU', 'ja': 'ビードル', 'ko': '뿔충이'},
    14: {'fr': 'COCONFORT', 'de': 'KOKUNA', 'ja': 'コクーン', 'ko': '딱충이'},
    15: {'fr': 'DARDARGNAN', 'de': 'BIBOR', 'ja': 'スピアー', 'ko': '독침붕'},
    16: {'fr': 'ROUCOOL', 'de': 'TAUBSI', 'ja': 'ポッポ', 'ko': '구구'},
    17: {'fr': 'ROUCOUPS', 'de': 'TAUBOGA', 'ja': 'ピジョン', 'ko': '피죤'},
    18: {'fr': 'ROUCARNAGE', 'de': 'TAUBOSS', 'ja': 'ピジョット', 'ko': '피죤투'},
    19: {'de': 'RATTFRATZ', 'ja': 'コラッタ', 'ko': '꼬렛'},
    20: {'fr': 'RATTATAC', 'de': 'RATTIKARL', 'ja': 'ラッタ', 'ko': '레트라'},
    21: {'fr': 'PIAFABEC', 'de': 'HABITAK', 'ja': 'オニスズメ', 'ko': '깨비참'},
    22: {'fr': 'RAPASDEPIC', 'de': 'IBITAK', 'ja': 'オニドリル', 'ko': '깨비드릴조'},
    23: {'fr': 'ABO', 'de': 'RETTAN', 'ja': 'アーボ', 'ko': '아보'},
    24: {'ja': 'アーボック', 'ko': '아보크'},
    25: {'ja': 'ピカチュウ', 'ko': '피카츄'},
    26: {'ja': 'ライチュウ', 'ko': '라이츄'},
    27: {'fr': 'SABELETTE', 'de': 'SANDAN', 'ja': 'サンド', 'ko': '모래두지'},
    28: {'fr': 'SABLAIREAU', 'de': 'SANDAMER', 'ja': 'サンドパン', 'ko': '고지'},
    29: {'ja': 'ニドランF', 'ko': '니드런 암'},
    30: {'ja': 'ニドリーナ', 'ko': '니드리나'},
    31: {'ja': 'ニドクイン', 'ko': '니드퀸'},
    32: {'ja': 'ニドランM', 'ko': '니드런 수'},
    33: {'ja': 'ニドリーノ', 'ko': '니드리노'},
    34: {'ja': 'ニドキング', 'ko': '니드킹'},
    35: {'fr': 'MELOFEE', 'de': 'PIEPI', 'ja': 'ピッピ', 'ko': '삐삐'},
    36: {'fr': 'MELODELFE', 'de': 'PIXI', 'ja': 'ピクシー', 'ko': '픽시'},
    37: {'fr': 'GOUPIX', 'ja': 'ロコン', 'ko': '식스테일'},
    38: {'fr': 'FEUNARD', 'de': 'VULNONA', 'ja': 'キュウコン', 'ko': '나인테일'},
    39: {'fr': 'RONDOUDOU', 'de': 'PUMMELUFF', 'ja': 'プリン', 'ko': '푸린'},
    40: {'fr': 'GRODOUDOU', 'de': 'KNUDDELUFF', 'ja': 'プクリン', 'ko': '푸크린'},
    41: {'fr': 'NOSFERAPTI', 'ja': 'ズバット', 'ko': '주뱃'},
    42: {'fr': 'NOSFERALTO', 'ja': 'ゴルバット', 'ko': '골뱃'},
    43: {'fr': 'MYSTHERBE', 'de': 'MYRAPLA', 'ja': 'ナゾノクサ', 'ko': '뚜벅쵸'},
    44: {'fr': 'ORTIDE', 'de': 'DUFLOR', 'ja': 'クサイハナ', 'ko': '냄새꼬'},
    45: {'fr': 'RAFFLESIA', 'de': 'GIFLOR', 'ja': 'ラフレシア', 'ko': '라플레시아'},
    46: {'ja': 'パラス', 'ko': '파라스'},
    47: {'de': 'PARASEK', 'ja': 'パラセクト', 'ko': '파라섹트'},
    48: {'fr': 'MIMITOSS', 'de': 'BLUZUK', 'ja': 'コンパン', 'ko': '콘팡'},
    49: {'fr': 'AEROMITE', 'de': 'OMOT', 'ja': 'モルフォン', 'ko': '도나리'},
    50: {'fr': 'TAUPIQUEUR', 'de': 'DIGDA', 'ja': 'ディグダ', 'ko': '디그다'},
    51: {'fr': 'TRIOPIKEUR', 'de': 'DIGDRI', 'ja': 'ダグトリオ', 'ko': '닥트리오'},
    52: {'fr': 'MIAOUSS', 'de': 'MAUZI', 'ja': 'ニャース', 'ko': '나옹'},
    53: {'de': 'SNOBILIKAT', 'ja': 'ペルシアン', 'ko': '페르시온'},
    54: {'fr': 'PSYKOKWAK', 'de': 'ENTON', 'ja': 'コダック', 'ko': '고라파덕'},
    55: {'fr': 'AKWAKWAK', 'de': 'ENTORON', 'ja': 'ゴルダック', 'ko': '골덕'},
    56: {'fr': 'FEROSINGE', 'de': 'MENKI', 'ja': 'マンキー', 'ko': '망키'},
    57: {'fr': 'COLOSSINGE', 'de': 'RASAFF', 'ja': 'オコリザル', 'ko': '성원숭'},
    58: {'fr': 'CANINOS', 'de': 'FUKANO', 'ja': 'ガーディ', 'ko': '가디'},
    59: {'fr': 'ARCANIN', 'de': 'ARKANI', 'ja': 'ウインディ', 'ko': '윈디'},
    60: {'fr': 'PTITARD', 'de': 'QUAPSEL', 'ja': 'ニョロモ', 'ko': '발챙이'},
    61: {'fr': 'TETARTE', 'de': 'QUAPUTZI', 'ja': 'ニョロゾ', 'ko': '슈륙챙이'},
    62: {'fr': 'TARTARD', 'de': 'QUAPPO', 'ja': 'ニョロボン', 'ko': '강챙이'},
    63: {'ja': 'ケーシィ', 'ko': '캐이시'},
    64: {'ja': 'ユンゲラー', 'ko': '윤겔라'},
    65: {'de': 'SIMSALA', 'ja': 'フーディン', 'ko': '후딘'},
    66: {'fr': 'MACHOC', 'de': 'MACHOLLO', 'ja': 'ワンリキー', 'ko': '알통몬'},
    67: {'fr': 'MACHOPEUR', 'de': 'MASCHOCK', 'ja': 'ゴーリキー', 'ko': '근육몬'},
    68: {'fr': 'MACKOGNEUR', 'de': 'MACHOMEI', 'ja': 'カイリキー', 'ko': '괴력몬'},
    69: {'fr': 'CHETIFLOR', 'de': 'KNOFENSA', 'ja': 'マダツボミ', 'ko': '모다피'},
    70: {'fr': 'BOUSTIFLOR', 'de': 'ULTRIGARIA', 'ja': 'ウツドン', 'ko': '우츠동'},
    71: {'fr': 'EMPIFLOR', 'de': 'SARZENIA', 'ja': 'ウツボット', 'ko': '우츠보트'},
    72: {'de': 'TENTACHA', 'ja': 'メノクラゲ', 'ko': '왕눈해'},
    73: {'de': 'TENTOXA', 'ja': 'ドククラゲ', 'ko': '독파리'},
    74: {'fr': 'RACAILLOU', 'de': 'KLEINSTEIN', 'ja': 'イシツブテ', 'ko': '꼬마돌'},
    75: {'fr': 'GRAVALANCH', 'de': 'GEOROK', 'ja': 'ゴローン', 'ko': '데구리'},
    76: {'fr': 'GROLEM', 'de': 'GEOWAZ', 'ja': 'ゴローニャ', 'ko': '딱구리'},
    77: {'de': 'PONITA', 'ja': 'ポニータ', 'ko': '포니타'},
    78: {'fr': 'GALOPA', 'de': 'GALLOPA', 'ja': 'ギャロップ', 'ko': '날쌩마'},
    79: {'fr': 'RAMOLOSS', 'de': 'FLEGMON', 'ja': 'ヤドン', 'ko': '야돈'},
    80: {'fr': 'FLAGADOSS', 'de': 'LAHMUS', 'ja': 'ヤドラン', 'ko': '야도란'},
    81: {'fr': 'MAGNETI', 'de': 'MAGNETILO', 'ja': 'コイル', 'ko': '코일'},
    82: {'ja': 'レアコイル', 'ko': '레어코일'},
    83: {'fr': 'CANARTICHO', 'de': 'PORENTA', 'ja': 'カモネギ', 'ko': '파오리'},
    84: {'de': 'DODU', 'ja': 'ドードー', 'ko': '두두'},
    85: {'de': 'DODRI', 'ja': 'ドードリオ', 'ko': '두트리오'},
    86: {'fr': 'OTARIA', 'de': 'JUROB', 'ja': 'パウワウ', 'ko': '쥬쥬'},
    87: {'fr': 'LAMANTINE', 'de': 'JUGONG', 'ja': 'ジュゴン', 'ko': '쥬레곤'},
    88: {'fr': 'TADMORV', 'de': 'SLEIMA', 'ja': 'ベトベター', 'ko': '질퍽이'},
    89: {'fr': 'GROTADMORV', 'de': 'SLEIMOK', 'ja': 'ベトベトン', 'ko': '질뻐기'},
    90: {'fr': 'KOKIYAS', 'de': 'MUSCHAS', 'ja': 'シェルダー', 'ko': '셀러'},
    91: {'fr': 'CRUSTABRI', 'de': 'AUSTOS', 'ja': 'パルシェン', 'ko': '파르셀'},
    92: {'fr': 'FANTOMINUS', 'de': 'NEBULAK', 'ja': 'ゴース', 'ko': '고오스'},
    93: {'fr': 'SPECTRUM', 'de': 'ALPOLLO', 'ja': 'ゴースト', 'ko': '고우스트'},
    94: {'fr': 'ECTOPLASMA', 'ja': 'ゲンガー', 'ko': '팬텀'},
    95: {'ja': 'イワーク', 'ko': '롱스톤'},
    96: {'fr': 'SOPORIFIK', 'de': 'TRAUMATO', 'ja': 'スリープ', 'ko': '슬리프'},
    97: {'fr': 'HYPNOMADE', 'ja': 'スリーパー', 'ko': '슬리퍼'},
    98: {'ja': 'クラブ', 'ko': '크랩'},
    99: {'fr': 'KRABBOSS', 'ja': 'キングラー', 'ko': '킹크랩'},
    100: {'fr': 'VOLTORBE', 'de': 'VOLTOBAL', 'ja': 'ビリリダマ', 'ko': '찌리리공'},
    101: {'de': 'LEKTROBAL', 'ja': 'マルマイン', 'ko': '붐볼'},
    102: {'fr': 'NOEUNOEUF', 'de': 'OWEI', 'ja': 'タマタマ', 'ko': '아라리'},
    103: {'fr': 'NOADKOKO', 'de': 'KOKOWEI', 'ja': 'ナッシー', 'ko': '나시'},
    104: {'fr': 'OSSELAIT', 'de': 'TRAGOSSO', 'ja': 'カラカラ', 'ko': '탕구리'},
    105: {'fr': 'OSSATUEUR', 'de': 'KNOGGA', 'ja': 'ガラガラ', 'ko': '텅구리'},
    106: {'fr': 'KICKLEE', 'de': 'KICKLEE', 'ja': 'サワムラー', 'ko': '시라소몬'},
    107: {'fr': 'TYGNON', 'de': 'NOCKCHAN', 'ja': 'エビワラー', 'ko': '홍수몬'},
    108: {'fr': 'EXCELANGUE', 'de': 'SCHLURP', 'ja': 'ベロリンガ', 'ko': '내루미'},
    109: {'fr': 'SMOGO', 'de': 'SMOGON', 'ja': 'ドガース', 'ko': '또가스'},
    110: {'fr': 'SMOGOGO', 'de': 'SMOGMOG', 'ja': 'マタドガス', 'ko': '또도가스'},
    111: {'fr': 'RHINOCORNE', 'de': 'RIHORN', 'ja': 'サイホーン', 'ko': '뿔카노'},
    112: {'fr': 'RHINOFEROS', 'de': 'RIZEROS', 'ja': 'サイドン', 'ko': '코뿌리'},
    113: {'fr': 'LEVEINARD', 'de': 'CHANEIRA', 'ja': 'ラッキー', 'ko': '럭키'},
    114: {'fr': 'SAQUEDENEU', 'ja': 'モンジャラ', 'ko': '덩쿠리'},
    115: {'fr': 'KANGOUREX', 'de': 'KANGAMA', 'ja': 'ガルーラ', 'ko': '캥카'},
    116: {'fr': 'HYPOTREMPE', 'de': 'SEEPER', 'ja': 'タッツー', 'ko': '쏘드라'},
    117: {'fr': 'HYPOCEAN', 'de': 'SEEMON', 'ja': 'シードラ', 'ko': '시드라'},
    118: {'fr': 'POISSIRENE', 'de': 'GOLDINI', 'ja': 'トサキント', 'ko': '콘치'},
    119: {'fr': 'POISSOROY', 'de': 'GOLKING', 'ja': 'アズマオウ', 'ko': '왕콘치'},
    120: {'fr': 'STARI', 'de': 'STERNDU', 'ja': 'ヒトデマン', 'ko': '별가사리'},
    121: {'fr': 'STAROSS', 'ja': 'スターミー', 'ko': '아쿠스타'},
    122: {'fr': 'M. MIME', 'de': 'PANTIMOS', 'ja': 'バリヤード', 'ko': '마임맨'},
    123: {'fr': 'INSECATEUR', 'de': 'SICHLOR', 'ja': 'ストライク', 'ko': '스라크'},
    124: {'fr': 'LIPPOUTOU', 'de': 'ROSSANA', 'ja': 'ルージュラ', 'ko': '루주라'},
    125: {'fr': 'ELEKTEK', 'de': 'ELEKTEK', 'ja': 'エレブー', 'ko': '에레브'},
    126: {'ja': 'ブーバー', 'ko': '마그마'},
    127: {'fr': 'SCARABRUTE', 'ja': 'カイロス', 'ko': '쁘사이저'},
    128: {'ja': 'ケンタロス', 'ko': '켄타로스'},
    129: {'fr': 'MAGICARPE', 'de': 'KARPADOR', 'ja': 'コイキング', 'ko': '잉어킹'},
    130: {'fr': 'LEVIATOR', 'de': 'GARADOS', 'ja': 'ギャラドス', 'ko': '갸라도스'},
    131: {'fr': 'LOKHLASS', 'ja': 'ラプラス', 'ko': '라프라스'},
    132: {'fr': 'METAMORPH', 'ja': 'メタモン', 'ko': '메타몽'},
    133: {'fr': 'EVOLI', 'de': 'EVOLI', 'ja': 'イーブイ', 'ko': '이브이'},
    134: {'fr': 'AQUALI', 'de': 'AQUANA', 'ja': 'シャワーズ', 'ko': '샤미드'},
    135: {'fr': 'VOLTALI', 'de': 'BLITZA', 'ja': 'サンダース', 'ko': '쥬피썬더'},
    136: {'fr': 'PYROLI', 'de': 'FLAMARA', 'ja': 'ブースター', 'ko': '부스터'},
    137: {'ja': 'ポリゴン', 'ko': '폴리곤'},
    138: {'fr': 'AMONITA', 'de': 'AMONITAS', 'ja': 'オムナイト', 'ko': '암나이트'},
    139: {'fr': 'AMONISTAR', 'de': 'AMOROSO', 'ja': 'オムスター', 'ko': '암스타'},
    140: {'ja': 'カブト', 'ko': '투구'},
    141: {'ja': 'カブトプス', 'ko': '투구푸스'},
    142: {'fr': 'PTERA', 'ja': 'プテラ', 'ko': '프테라'},
    143: {'fr': 'RONFLEX', 'de': 'RELAXO', 'ja': 'カビゴン', 'ko': '잠만보'},
    144: {'fr': 'ARTIKODIN', 'de': 'ARKTOS', 'ja': 'フリーザー', 'ko': '프리져'},
    145: {'fr': 'ELECTHOR', 'ja': 'サンダー', 'ko': '썬더'},
    146: {'fr': 'SULFURA', 'de': 'LAVADOS', 'ja': 'ファイヤー', 'ko': '파이어'},
    147: {'fr': 'MINIDRACO', 'ja': 'ミニリュウ', 'ko': '미뇽'},
    148: {'fr': 'DRACO', 'de': 'DRAGONIR', 'ja': 'ハクリュー', 'ko': '신뇽'},
    149: {'fr': 'DRACOLOSSE', 'de': 'DRAGORAN', 'ja': 'カイリュー', 'ko': '망나뇽'},
    150: {'de': 'MEWTU', 'ja': 'ミュウツー', 'ko': '뮤츠'},
    151: {'ja': 'ミュウ', 'ko': '뮤'},
}
